services:
  latinparser-be:
    build:
      context: ..\latin-parser-app\kotlin
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network

  latinparser-fe:
    build:
      context: ..\latin-parser-app\vue
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
